### ISSUE TITLE
Problem with audio with opus

### ISSUE THREAD

**Issue by scgm11** [seanbright/asterisk-opus#19] opened 2016-05-18 21:41 UTC
Using webrtc with opus transcoding between alaw and opus, when more volume the audio saturates, anyone has the same problem? this is with asterisk 13.9.0, chan_sip.

wil be doing more tests these days, what kind of log would be good to track down this issue?

thanks

**Comment by traud** [comment] 2016-05-25 06:55
Good question. No idea which log would help here. Therefore a different approach: Please, post as short but precise as you can, so I am able to re-build your setup and reproduce your issue here easily. Sounds like an issue within Opus-Codec itself.

**Comment by scgm11** [comment] 2016-05-25 15:23
I have 2 peers, 1001 and 1002 one with only opus one with only alaw
190.134.113.190  1002             979105562@190.1  (alaw)           No       Rx: ACK                    1002      
190.134.113.190  1001             0075be616aff574  (opus)           No       Tx: ACK                    1001      


1001 when 1002 is talking the volume saturates and the sound is bad, this doesn't happen going alaw alaw

Peer             User/ANR         Call ID          Format           Hold     Last Message    Expiry     Peer      
190.134.113.190  1003             k7d28u262llepnf  (opus)           No       Rx: ACK                    1003      
190.134.113.190  1001             39ffaa245e87658  (opus)           No       Tx: ACK                    1001      
2 active SIP dialogs

in this case is not happening so I think is transcoding related, no change in volume from dialplan, only Dial, this should be easy to reproduce I think there is nothing related with my config.

thanks

**Comment by traud** [comment] 2016-05-30 07:41
First, I have to understand the symptoms. Second, I have to reproduce it. Although I have not understand yet (what do you mean with ‘more volume, audio saturates’ exactly), I tried to reproduce this issue: I faced no problems from A-law (20 ms packetization time; ptime 20) to Opus-Codec. Perhaps you could attach two recorded audio files, one with A-law-no-transcoding and one with A-law/Opus-Codec. Alternatively, you have to describe it in text and greater detail.

**Comment by scgm11** [comment] 2016-06-01 21:09
I've changed the server machine and started working ok, Im closing this for now if I can reproduce it again I will reopen it. Thanks

**Comment by scgm11** [comment] 2016-06-07 14:45
Attached 3 test, opus <-> alaw,  alaw <-> alaw,  opus <-> ulaw

all transcodings sounds bad, the server is a cloud machine on GCP, could this be related?
please change txt to mp3 so you can see the noise.

thanks

[1001 opus (hears bad)-1002 ulaw.txt](https://github.com/seanbright/asterisk-opus/files/302856/1001.opus.hears.bad.-1002.ulaw.txt)
[1001alaw-1002 alaw.txt](https://github.com/seanbright/asterisk-opus/files/302858/1001alaw-1002.alaw.txt)
[1001 (hearsbad) opus-1002 alaw.txt](https://github.com/seanbright/asterisk-opus/files/302857/1001.hearsbad.opus-1002.alaw.txt)

**Comment by scgm11** [comment] 2016-07-12 15:16
any idea on this?

**Comment by traud** [comment] 2016-07-28 07:15
Opus Codec has a lot of properties which are negotiated via SDP. I guess, you use SIP – then, the SDP part of the SIP INVITE messages would be interesting. Second question: Which clients (web browsers, versions, platform) do you use? Third: Who starts the calls, the Opus party or the A-law party?

**Comment by scgm11** [comment] 2016-07-28 14:58
ok, the issue is:

Webrtc -> Webrtc   translation OK no strange sounds
SIP TLS SRTP (Yealink SIP-T20P 9.72.0.80) -> Webrtc has the problems

attach the webrtc SDP

[sdp.txt](https://github.com/seanbright/asterisk-opus/files/388656/sdp.txt)

**Comment by traud** [comment] 2016-08-22 12:40
Mhm. Your phone advertises a ptime of 10ms. Please, double-check with Wireshark whether the RTP packets from your phone arrive in 10ms or 20ms. I never tested anything below 20ms.

Another possible cause which I see from the logs:
Does Asterisk or your phone start this call? Would be interesting to see that SDP (or more precise the line `fmtp` of the Opus-Codec). Could be an issue in FEC as well. Alternatively, you edit [res/res_format_attr_opus.c](https://github.com/asterisk/asterisk/blob/master/res/res_format_attr_opus.c), change `.fec` in `default_opus_attr` from 1 to 0, and issue `sudo make install` within your Asterisk source path. Then, Asterisk requests no FEC, when Asterisk starts the call.

**Comment by traud** [comment] 2016-10-21 07:57
Do you still face that issue, even in Asterisk 13.12 with opus_codec module from Digium?

**Comment by scgm11** [comment] 2016-10-21 08:03
I will try it as soon is released (in case anything changes) sorry for the delay but I've missed the previous comment, thanks for the follow up

**Comment by traud** [comment] 2016-10-21 17:30
OK. Just for your information, Asterisk 13.12 is available as Release-Candidate already. It is always good to test early, so bugs can be resolved as soon as possible. If you have the time, please, answer my questions above anyway. It would be interesting to solve such an issue even for the Open Source variant of opus_codec.

**Comment by scgm11** [comment] 2016-10-26 14:57
Ok Im trying now with 13.12 opus seems registered fine, codecs.conf doesn't have any options for this, and Im getting when answering Bad Media Description, I add the SDP on my client side, when it works (OSSDP), and newSDPs that is with the new digium opus codec, the only differences I can see from this side is : 

New: a=fmtp:111
OS: a=fmtp:111 useinbandfec=1

New: a=maxptime:20
OS: a=maxptime:60

OS works, New gives Bad Media Description

[newSDPs.txt](https://github.com/seanbright/asterisk-opus/files/553635/newSDPs.txt)
[OSSDP.txt](https://github.com/seanbright/asterisk-opus/files/553636/OSSDP.txt)

**Comment by traud** [comment] 2016-11-02 14:17
Because that Opus-Codec module is closed source, I cannot look into it. You have to report that SDP negotiation issue somewhere else. Not sure, but I would start with the [Asterisk Issue Tracker…](//issues.asterisk.org/)

If you want to continue with the Open-Source module in this repository and you are interested in solving this issue, please, answer the questions above:
1. In Wireshark, you see RTP packets every xx milliseconds.
2. Does Asterisk or your phone start this call? From the logs, it looks like your phone.
3. Are you using the latest version from this repository here or ‘my’ [latest version](/traud/asterisk-opus)?

**Comment by scgm11** [comment] 2016-11-02 19:06
to follow up:
https://issues.asterisk.org/jira/browse/ASTERISK-26520?filter=11340

I will first go with the new module, are you planing to maintain this repo anyway?

**Comment by traud** [comment] 2016-11-02 20:35
Yes, I continue to maintain [traud/asterisk-opus](/traud/asterisk-opus). I am closing this report for now. When you come back to this module here (or somebody else faces the same issue), please, re-open.

**Closed by traud** 2016-11-02 20:35 UTC
